# This file has magic strings that we later substitute out at Docker runtime

GOOGLE_API_KEY: 'GOOGLE_API_KEY_REPLACE_ME'

ALGOLIA_INDEX_PREFIX: 'ALGOLIA_INDEX_PREFIX_REPLACE_ME'
ALGOLIA_APPLICATION_ID: 'ALGOLIA_APPLICATION_ID_REPLACE_ME'
ALGOLIA_READ_ONLY_API_KEY: 'ALGOLIA_READ_ONLY_API_KEY_REPLACE_ME'

# this is not sensitive data, so we just pass it in as is
MOHCD_SUBDOMAIN: 'sfserviceguide'
