# This file contains the config needed to configure the UI.
# Environment variables will override this config if they exist
# You need to create a config.yml file with your own values to run locally

# This key needs access to the following APIs:
# - Maps JavaScript API
# - Street View API
# Note that the settings for this key are in Google Cloud Platform under the
# AskDarcel Staging project
GOOGLE_API_KEY: 'AIzaSyBeryKXoJ8TRlRCC4NLM5tBi0vZWB-Ft5c'

ALGOLIA_INDEX_PREFIX: '<ENTER_YOUR_GITHUB_USERNAME_HERE>'
ALGOLIA_APPLICATION_ID: 'J8TVT53HPZ'
ALGOLIA_READ_ONLY_API_KEY: 'fdf77b152ff7ce0ea4e4221ff3d17d85'

MOHCD_SUBDOMAIN: 'testing'

# uncomment this to simulate sfserviceguide whitelabel UI locally, assuming that
# you're pointing to localhost:8080
# MOHCD_DOMAIN: 'localhost:8080'
