# This file has magic strings that we later substitute out at Docker runtime

GOOGLE_API_KEY: 'GOOGLE_API_KEY_REPLACE_ME'

ALGOLIA_INDEX_PREFIX: 'ALGOLIA_INDEX_PREFIX_REPLACE_ME'
ALGOLIA_APPLICATION_ID: 'ALGOLIA_APPLICATION_ID_REPLACE_ME'
ALGOLIA_READ_ONLY_API_KEY: 'ALGOLIA_READ_ONLY_API_KEY_REPLACE_ME'

MOHCD_SUBDOMAIN: 'MOHCD_SUBDOMAIN_REPLACE_ME'
